### ISSUE TITLE
[Bug] Drift with right thumbstick

### ISSUE THREAD

**Issue by Andiweli** [JetStreamSham/ZGloom-vita#10]
At first I thought my hardware is faulty, but yesterday I built in a brand new thumbstick - and it is still happening.
When rotating with the right stick, it sometimes drifts by itself.
This doesn't happen in any other FPS game.

Perhaps the deadzone is too low?
I tried raising the values:

`
static unsigned char rightStickDeadzone = 20;
static unsigned char leftStickDeadzone = 20;
`
...but no success.

PS: I already lowered the sensitivity to 2, but that doesn't help.
PPS: setting the global (PSVITA-wide) deadzone with analogsenhancer.skprx to "20" fixes the problem.

**Comment by Andiweli** [comment]
Btw, the rotation doesn't drift with the "old" controller code where the touchpad was active...

**Comment by JetStreamSham** [comment]
potentially fixed in https://github.com/JetStreamSham/ZGloom-vita/commit/380ce1837f08bc15c2f9485f7bb9d76940f361e4 ....

**Comment by Andiweli** [comment]
Wait, let me finish daily business... will compile then and get back 👍🏻

**Comment by Andiweli** [comment]
> potentially fixed in [380ce18](https://github.com/JetStreamSham/ZGloom-vita/commit/380ce1837f08bc15c2f9485f7bb9d76940f361e4) ....

Yes, that fixes the drift! 👍🏻
