### ISSUE TITLE
1.0.1 > Key config not working

### ISSUE THREAD

**Issue by Andiweli** [JetStreamSham/ZGloom-vita#4]
1. ~~With the latest 1.0.1 release the right stick isn't recognized anymore.
Just the left one.~~
2. Also "Control config" > "Configure keys" is closed immediately.
Can't reconfigure the keys.
3. ~~ControlFire is also not working > was right trigger before.
Can't be reconfigured because keyconfig not working.~~
4. ~~About screen in menu also not working > closing immediately.~~

**Comment by Andiweli** [comment]
In Line 735 add - then right controllerstick is working again:

		Input::Stick rightStick = Input::GetRightStick();
			
		if (rightStick.x < 125 - Config::GetRightStickDeadzone())
			controlleft = true;
		if (rightStick.x > 125 + Config::GetRightStickDeadzone())
			controlright = true;

I made a pull request regarding this issue.

**Comment by JetStreamSham** [comment]
2. was fixed in https://github.com/JetStreamSham/ZGloom-vita/commit/64d3d1a4efe084fef4219cde1a9736fc9128c828

could you separate these 4 issues into their own issue

**Comment by Andiweli** [comment]
Done!

1. was fixed with yesterdays pull request
2. was fixed by you
3. and 4. are now separate issues
