### ISSUE TITLE
1.0.1 > Trigger/ControlFire not working anymore

### ISSUE THREAD

**Issue by Andiweli** [JetStreamSham/ZGloom-vita#7]
ControlFire is also not working > was right trigger before.
Can't be reconfigured because keyconfig not working.

**Comment by JetStreamSham** [comment]
The default fire key on the vita as of 1.0.1 is the CROSS/X button.
key configuration has been fixed in https://github.com/JetStreamSham/ZGloom-vita/commit/64d3d1a4efe084fef4219cde1a9736fc9128c828  and ControlFire can be rebound to a trigger now.

**Comment by Andiweli** [comment]
Thanks! I will try to compile it...

**Comment by Andiweli** [comment]
Working and compiled.
Settings are saved when exiting the game.

PS: I get many compiling warnings or so - is that normal?

**Comment by JetStreamSham** [comment]
It's normal I get warnings too.
