### ISSUE TITLE
[Bug] Pressing START in menu  leads to crash

### ISSUE THREAD

**Issue by Andiweli** [JetStreamSham/ZGloom-vita#9]
As mentioned in the title.

If you are in the game > Quit to Title > press START in menu... then you get back to the game.

**Comment by JetStreamSham** [comment]
fixed in https://github.com/JetStreamSham/ZGloom-vita/commit/8661e08fc6c16c27539d51516db36e82b58e9b54

**Comment by Andiweli** [comment]
Working :)
